config/routes.rb
Rails.application.routes.draw do
 
  resources :assignments
  resources :roles
  
  devise_for :users, :path_prefix => 'my'
  resources :users
  
  resources :personas do
    get :buscar_persona, on: :collection
  end
  resources :eventos
  resources :cargos
  
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'constancia', to: 'personas#constancia', as: 'constancia'
  
  post 'personas/traer_datos', to: 'personas#traer_datos'
  
  root :to => 'static_pages#home'

end

app/models/cargo.rb
class Cargo < ApplicationRecord
    
    def self.search(search, page)
      where(['upper(nombre) like ?',
        "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("nombre")
    end
    
    def name
      self.nombre
    end
    
    validates :nombre, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
    validates :nombre, presence: true
    validates :dependencia, presence: true
end
=begin Codigo:
1. Para la paginacion, ordena por nombre. 
2. Valida que el nombre sea unico y que los campos esten llenos. 
3. Para hacer una busqueda del cargo por nombre
=end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  def index
    @cargos = Cargo.search(params[:search], params[:page])
  end

  def show
  end

  def new
    @cargo = Cargo.new
  end

  def edit
  end

  def create
    @cargo = Cargo.new(cargo_params)
    respond_to do |format|
      if @cargo.save
        format.html { redirect_to cargos_url, notice: 'El cargo fue creado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to cargos_url, notice: 'El cargo fue actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'El cargo fue eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end
    
    def cargo_params
      params.require(:cargo).permit(:nombre, :dependencia)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
<br>
  <div class="col-md-offset-4 col-md-4">
    <%= form_for(@cargo) do |f| %>
      <% if cargo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(cargo.errors.count, "Error en los siguientes campos:") %></h2>
            <ul>
              <% cargo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
        <%= f.label :nombre %>
        <%= f.text_field :nombre, :required => true, class:'form-control' %>
      <br><br>
        <%= f.label :dependencia %>
        <%= f.text_field :dependencia, class:'form-control' %>
      <br>
        <ul>
          <%= button_tag(type: "submit", class: "clase-boton") do %>
            <i class="fa fa-floppy-o fa-2x" title="GUARDAR"></i>
          <% end %>
          &nbsp; &nbsp;
          <%= link_to '<i class="fa fa-reply fa-2x" title="ATRAS"></i>'.html_safe, cargos_path %>
        </ul>
          <% if @mostrar == true %>
            <%= link_to '<i class="fa fa-eye fa-2x" title="MOSTRAR"></i>'.html_safe, @cargo %>
          <% end %>
      <br><br>
    <% end %>      
  </div>
<%#Terminado, formulario que muestra al querer agregar y editar.#%>

app/views/cargos/_show.html.erb
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <h3 class="modal-title"><center>INFORMACIÓN DEL CARGO</center></h3>
        </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-md-6">   
                <strong><center>Nombre:</center></strong>
                <center><%= @cargo.nombre %></center>
              </div>
              <div class="col-md-6">
                <strong><center>Dependencia:</center></strong>
                <center><%= @cargo.dependencia %></center>
              </div>
            </div>
              <div class="modal-footer"></div>
          </div>
      </div>
    </div>
  </div>
<%#Terminado, formulario que muestra la ventana modal.#%>

app/views/cargos/edit.html.erb
<br>
<br>
<h2><center><b>EDITAR CARGO</b></center></h2>
<%= render 'form', cargo: @cargo %>
<%#Terminado, codigo para renderizar al formulario show.html cuando se va a editar#%>

app/views/cargos/index.html.erb
<br>
  <h2><center><b>LISTA DE CARGOS</b></center></h2>
    <div class="well well-sm, col-md-offset-4">
      <%= form_tag cargos_path, class: "form-inline", method: 'get' do %>
        <label>BUSCAR:</label>
          <%= search_field_tag :search, params[:search], :class => "form-control", placeholder: "Ingrese cargo", size: "31" %>
            <button class="btn btn-success btn-sm">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </button>
      <% end %>
    </div>
      <br>
       <div class="table-responsive">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th class="center">NOMBRE</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @cargos.each do |cargo| %>
              <tr>
                <td class="center"><%= cargo.nombre %></td>
                <td><%= link_to '<i class="fa fa-eye fa-2x" title="MOSTRAR"></i>'.html_safe, cargo, remote: true %></td>
                <td><%= link_to '<i class="fa fa-pencil-square fa-2x" title="EDITAR"></i>'.html_safe, edit_cargo_path(cargo) %></td>
                <td><%= link_to '<i class="fa fa-times fa-2x" title="ELIMINAR"></i>'.html_safe, cargo, method: :delete, data: { confirm: 'Está seguro de eliminar este registro?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>  
      <br>
    <%= link_to '<i class="fa fa-plus-square fa-2x" title="AGREGAR CARGO"></i>'.html_safe, new_cargo_path %>
    &nbsp; &nbsp; <%= link_to '<i class="fa fa-reply fa-2x" title="ATRAS"></i>'.html_safe, cargos_path %>
  &nbsp; &nbsp; Cargos: <%= @cargos.count %>
&nbsp; &nbsp; <%=will_paginate@cargos, :previous_label =>'&laquo; Anterior',:next_label =>'Siguiente &raquo;' %>
<%# 1.codigo para mostrar la lista de cargos. #%> 
<%# 2.codigo para el buscado por nombre, y el boton (lupa). #%>
<%# 3.codigo para la tabla, mostrar, editar, eliminar. #%>
<%# 4.codigo para agregar un nuevo registro y me lleva al form. #%>
<%# 5.codigo para contar cantidad de cargos y cantidad de paginar llenas #%>

app/views/cargos/new.html.erb
<br>
<br>
<h2><center><b>NUEVO CARGO</b></center></h2>
<%= render 'form', cargo: @cargo %>
<%#Terminado#%>