config/routes.rb
Rails.application.routes.draw do
 
  resources :assignments
  resources :roles
  
  devise_for :users, :path_prefix => 'my'
  resources :users
  
  resources :personas do
    get :buscar_persona, on: :collection
  end
  resources :eventos
  resources :cargos
  
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'constancia', to: 'personas#constancia', as: 'constancia'
  
  post 'personas/traer_datos', to: 'personas#traer_datos'
  
  root :to => 'static_pages#home'

end

app/models/evento.rb
class Evento < ApplicationRecord
    
    def self.search(search, page)
      where(['upper(asunto) like ?',
         "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("asunto")
    end
     
    validates :asunto, presence: true
    validates :fecha, presence: true
    validates :hora, presence: true
    validates :ubicacion, presence: true 
    
    def name
      self.asunto
    end
    
   has_many :eventos_personas, dependent: :destroy
   has_many :personas, through: :eventos_personas

   def personas_for_form
     collection = personas.where(evento_id: id)
     collection.any? ? collection : personas.build
   end

=begin
    Se debe reconsiderar el uso de este método pues cambia la fecha y hora para la actual cuando 
    va a ser guardado el evento

    before_create :guardar_por_debajo
    
    def guardar_por_debajo
        Time.zone = "America/Bogota"   # permite atrapar zona horaria de colombia
        # Esta es la linea que impide que un evento sea guardado con la fecha que se le
        # asigna, en vista de que el guarda la fecha que se le dice aquí
        # self.fecha = Time.zone.now.strftime("%Y-%m-%d") #Esto asigna la fecha

        # Esta linea tiene el mismo efecto en la hora
        # self.hora = Time.zone.now.strftime("%H:%M:%S") #Asigna hora
    end
=end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  def index
    @eventos = Evento.search(params[:search], params[:page])
  end
  
  def show
   
  end

  def new
    @evento = Evento.new
  end

  def edit
    @evento.fecha.strftime("%d/%m/%Y")
    @evento.hora
    puts "esta es la fecha #{@evento.fecha}"
  end

  def create
    @evento = Evento.new(evento_params)
    respond_to do |format|
      if @evento.save
        format.html { redirect_to eventos_url, notice: 'El evento fue creado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      begin
        if @evento.update(evento_params)
          format.html { redirect_to eventos_url, notice: 'El evento fue modificado correctamente.' }
          format.json { head :no_content }
        else
          format.html { render :edit }
          format.json { render json: @evento.errors, status: :unprocessable_entity }
        end
      rescue
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'El evento fue eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_evento
      @evento = Evento.find(params[:id])
    end

    def evento_params
      params.require(:evento).permit(:asunto, :fecha, :hora, :ubicacion, :persona_ids => [])
    end    
end

app/helpers/eventos_helper.rb
module EventosHelper
   def link_to_add_fields(name, f, association)
	new_object = f.object.send(association).klass.new
	id = new_object.object_id
	fields = f.fields_for(association, new_object, child_index: id) do |personas_for_form|
 	render(association.to_s.singularize + "_fields", f: personas_for_form)
	end
	link_to(name, '', class: "add_fields btn btn-primary",  data: { id: id, fields: fields.gsub("\n", "")})
   end
end

app/views/eventos/_form.html.erb
<br>
  <div class="col-md-offset">
    <%= simple_form_for(@evento) do |f| %>
      <% if evento.errors.any? %>
        <div id="error_explanation">
          <h3><%= pluralize(evento.errors.count, "No se puede guardar los datos, error en los siguientes campos:") %></h3>
            <ul>
              <% evento.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
        <div class="col-md-offset-2 col-md-9">
          <div class="row">
            <div class="col-md-3">
              <%= f.label :nombre, :required => true %>
              <%= f.text_field :asunto, class:'form-control' %>
            </div>
            <div class="col-md-3 col-sm-10">
              <%= f.input :fecha, as: :datetime_picker, readonly: true,
                input_html: {
                  data: {date_options: {format: 'DD/MM/YYYY', ignoreReadonly: true}}} %>
            </div>
            <div class="col-md-3">
              <%= f.label :ubicacion %>
              <%= f.text_field :ubicacion, :required => true, class:'form-control' %>
            </div>
            <div class="col-md-3">
              <%= f.input :hora %>
            </div> 
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <br><br><center><label for="persona_datos"><h4><b>Ingrese Documento o Código</b></h4></label></center> 
              <%= content_tag :input, "",name: "persona_datos", id:"persona_datos", class: "form-control"%>
          </div>
          <% personas = @evento.personas %>
            <% personas_empty = personas.empty?  %>
              <div class="col-md-12"><br><br>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered" id="evento_personas"><br>
                    <thead>
                      <tr>
                        <th class="text-center">Hora</th>
                        <th class="text-center">Nombre</th>
                        <th class="text-center">Documento</th>
                        <th class="text-center">Codigo</th>
                        <th class="text-center">Cargo</th>
                        <th class="text-center" colspan="2"></th>
                      </tr>
                    </thead>
                      <tbody>
                        <% if personas_empty %>
                          <tr id="fila_vacia" class="text-center">
                            <td colspan="6"> No se han añadido personas a este evento </td>
                          </tr>
                            <% else %>
                              <% personas.each do |persona| %>
                                <tr id="<%= persona.id %>" class="text-center">
                                  <td><%= persona.hora_evento(@evento) %> </td>
                                  <td><%= persona.nombres %> </td>
                                  <td><%= persona.documento %> </td>
                                  <td><%= persona.codigo %> </td>
                                  <td><%= persona.cargo.try(:name) %> </td>
                                  <td>
                                    <%= button_tag(type: "button", class: "clase-boton eliminar") do %>
                                      <i class="fa fa-times fa-2x" title="GUARDAR"></i>
                                    <% end %>
                                  </td>
                                </tr>
                              <% end %>
                        <% end %>
                      </tbody>
                      <tfoot>
                        <tr>
                          <td colspan="6" class="text-right">
                            <strong>A.P</strong> Asignación pendiente. La hora se asigna una vez se guarda el evento <br>
                            Una persona solo puede asistir a un evento una vez
                          </td>
                        </tr>
                      </tfoot>
                  </table>
                </div>
                  <% personas.each do |persona| %>
                    <% per_id = persona.id  %>
                      <%= f.hidden_field :persona_ids, multiple: true, value: per_id, id: "evento_persona_#{per_id}" %>        
                  <% end %>
              </div>
        </div>  
      <%= button_tag(type: "submit", class: "clase-boton", id: "submit_valido") do %>
        <i class="fa fa-floppy-o fa-2x" title="GUARDAR"></i>
      <% end %>
        &nbsp; &nbsp;
      <%= link_to '<i class="fa fa-reply fa-2x" title="ATRAS"></i>'.html_safe, eventos_path %>
    <% end %>
  </div>              

app/views/eventos/_persona_fields.html.erb
<fieldset>
  <div class="row">
    <div class="col-md-3">
      <%=f.input :hora, input_html:{data:{hora: true}} %>
    </div> 
    <div class="col-md-3">
      <%= f.label :nombre %>
      <%= f.text_field :nombres, data:{nombre: true}, label: false, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.input :documento, input_html:{data:{documento: true}} %>
    </div>
    <div class="col-md-3">
      <%= f.label :empresa %>
      <%= f.text_field :empresa, data:{empresa: true}, label: false, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.label :email %>
      <%= f.text_field :email, data:{email: true}, label: false, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :telefono %>
      <%= f.text_field :telefono, data:{telefono: true}, label: false, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.input :codigo, input_html:{data:{codigo: true}} %>
    </div>
    <div class="col-md-2">
      <%= f.association :cargo, input_html:{data:{cargo: true}}, :prompt=>"Seleccione un Cargo" %>
    </div>
    <div class="col-md-">
      <%= f.hidden_field :_destroy %>
        <%= link_to "Eliminar", '#', class: "remove_fields btn btn-danger" %>
    </div>
  </div>
  <hr>
</fieldset>
<%#ok%>

app/views/eventos/edit.html.erb
<br>
<h2><center><b>EDITAR EVENTO</b></center></h2>
<%= render 'form', evento: @evento %>
<%#ok%>

app/views/eventos/index.html.erb
<br>
  <h2 class="text-center"><b>LISTA DE EVENTOS</b></h2>
<br><br>
  <div class="well well-sm, col-md-offset-4">
    <%= form_tag eventos_path, class: "form-inline", method: 'get' do %>
      <label>BUSCAR:</label>
        <%= search_field_tag :search, params[:search], :class => "form-control", placeholder: "Ingrese nombre", size: "31" %>
          <button class="btn btn-success btn-sm">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
    <% end %>
  </div>
  <br>
   <div class="table-responsive">
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th class="center">NOMBRE</th>
          <th class="center">FECHA</th>
          <th class="center">HORA</th>
          <th class="center">UBICACION</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @eventos.each do |evento| %>
          <tr>
            <td class="center"><%= evento.asunto %></td>
            <td class="center"><%= evento.fecha.try(:strftime, '%d/%m/%Y') %></td>
            <td class="center"><%= evento.hora %></td>
            <td class="center"><%= evento.ubicacion %></td>
            <% if can? :manage, :all %>
              <td><%= link_to'<i class="fa fa-eye fa-2x" title="MOSTRAR"></i>'.html_safe, evento %></td>
              <td><%= link_to '<i class="fa fa-pencil-square fa-2x" title="EDITAR"></i>'.html_safe, edit_evento_path(evento) %></td>
              <td><%= link_to '<i class="fa fa-times fa-2x" title="ELIMINAR"></i>'.html_safe, evento, method: :delete, data: { confirm: 'Está seguro de eliminar este registro?' } %></td>
            <% elsif can? :read, Evento%>
              <td><%= link_to'<i class="fa fa-eye fa-2x" title="MOSTRAR"></i>'.html_safe, evento, remote: true %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
    <br>
    <% if can? :manage, :all %>
      <%= link_to '<i class="fa fa-plus-square fa-2x" title="AGREGAR EVENTO"></i>'.html_safe, new_evento_path %>
    <% end %>           
&nbsp; &nbsp; <%= link_to '<i class="fa fa-reply fa-2x" title="ATRAS"></i>'.html_safe, eventos_path %>
&nbsp; &nbsp; Eventos: <%= @eventos.count %>
&nbsp; &nbsp; <%=will_paginate@eventos,:previous_label =>'&laquo; Anterior',:next_label =>'Siguiente &raquo;' %>
<%#ok%>

app/views/eventos/new.html.erb
<br>
<h2><center><b>EVENTO NUEVO</b></center></h2>
<%= render 'form', evento: @evento %>
<%#ok%>

app/views/eventos/show.html.erb
<br>
  <div class="well well-sm, col-md-offset-4">
    <h3><center><b>EVENTO</b></center></h3>
  </div>  
    <div class="row">
      <div class="col-md-3">        
        <strong class="center"><h4><b>Nombre:</b></h4></strong>
        <center><%= @evento.asunto %></center>
      </div>
      <div class="col-md-3">
        <strong class="center"><h4><b>Fecha:</b></h4></strong>
        <center><%= @evento.fecha.try(:strftime, '%d/%m/%Y') %></center>
      </div>
      <div class="col-md-3">
        <strong class="center"><h4><b>Hora:</b></h4></strong>
        <center><%= @evento.hora %></center>
      </div>
      <div class="col-md-3">
        <strong class="center"><h4><b>Ubicacion:</b></h4></strong>
        <center><%= @evento.ubicacion %></center>
      </div>
    </div>
    <br><hr>
    <div class="well well-sm, col-md-offset-4">
      <h4><center><b>Lista de asistencia</b></center></h4>
    </div>  
    <% if @evento.personas.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="center">Hora</th>
            <th class="center">Nombre</th>
            <th class="center">Documento</th>
            <th class="center">Empresa</th>
            <th class="center">Email</th>
            <th class="center">Telefono</th>
            <th class="center">Código</th>
            <th class="center">Cargo</th>
            <th class="center"></th>
            <th class="center">Imprimir</th>
          </tr>
        </thead>
        <% @evento.personas.each do |persona| %>
          <tbody2>
            <tr>
              <td class="center"><%= persona.hora_evento(@evento) %></td>
              <td class="center"><%= persona.nombres %></td>
              <td class="center"><%= persona.documento %></td>
              <td class="center"><%= persona.empresa %></td>
              <td class="center"><%= persona.email %></td>
              <td class="center"><%= persona.telefono %></td>
              <td class="center"><%= persona.codigo %></td>
              <td class="center"><%= persona.cargo.try(:name) %></td>
              <% if can? :manage, :all %>
              <td><%= link_to '<i class="fa fa-eye fa-2x" title="MOSTRAR"></i>'.html_safe, persona, remote: true %> </td>
               <% end %>
              <td class="center"><%= link_to '<i class="fa fa-file-pdf-o" aria-hidden="true"></i>Constancia'.html_safe, persona_path(@persona, format: 'pdf', id: persona.id), :target => '_blank', class:"btn btn-info" %></td>
            </tr>
          </tbody2>
        <% end %>
      </table>
    </div>  
        <% else %>
          <p>No hay asistencias</p>
        <% end %>
        <% if can? :manage, :all %>
          &nbsp; &nbsp; <%= link_to '<i class="fa fa-pencil-square fa-2x" title="EDITAR"></i>'.html_safe, edit_evento_path(@evento) %>
        <% end %>
&nbsp; &nbsp; <%= link_to '<i class="fa fa-reply fa-2x" title="ATRAS"></i>'.html_safe, eventos_path %>
<%#ok%>