config/routes.rb
Rails.application.routes.draw do
 
  resources :assignments
  resources :roles
  
  devise_for :users, :path_prefix => 'my'
  resources :users
  
  resources :personas do
    get :buscar_persona, on: :collection
  end
  resources :eventos
  resources :cargos
  
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'constancia', to: 'personas#constancia', as: 'constancia'
  
  post 'personas/traer_datos', to: 'personas#traer_datos'
  
  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar">
  <%= image_tag("footerOk.png", class:'footer')%>
</footer>
<%#terminado#%>

app/views/layouts/_header.html.erb
<header>
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><strong><%= current_user.name %></strong><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Editar perfil', edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Registrarse", new_user_registration_path %></li>
              <li><%= link_to "Iniciar sesion", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav navbar-left ">
  <li><%= image_tag('logo_senn.png', class:'img-responsive logo_f') %></li>
  <li><%= image_tag("logoultimo-01.png", class:"mini_m") %></li>
</ul> 
  <% if can? :manage, :all %>
    <li><%= link_to "Inicio", root_path %></li>
    <li><%= link_to "Eventos", eventos_path %></li>
    <li><%= link_to "Personas", personas_path %></li>
    <li><%= link_to "Cargos", cargos_path %></li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Seguridad<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Usuarios", users_path %></li>
          <li><%= link_to "Roles", roles_path %></li>
          <li><%= link_to "Permisos", assignments_path %></li>
        </ul>
    </li>
  <% elsif can? :read, Evento%>
    <li><%= link_to "Eventos", eventos_path %></li>
<% end %>
<%#terminado#%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Codasis" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Codasis" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% puts "renderiza app"  %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
     <%= render 'layouts/messages' %>
     <%= render 'layouts/header' %>
     <%= yield %>
    </main>
	    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>
<%# Codigo requerido para el PDF %>